services:
  app:
    build:
      context: .
    image: contributions-cron:latest
    container_name: contributions-cron
    restart: unless-stopped
    environment:
      DB_URL: mongodb://mongodb:27017
      PORT: 8080
      GITHUB_API_KEY: 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
    networks:
      - contributions-network
    ports:
      - "8080:8080"
  
  mongodb:
    image: mongo
    container_name: mongoedb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: top-contributors
    networks:
      - contributions-network
    ports:
      - "27017:27017"

networks:
  contributions-network:
    driver: bridge
